language: python
python: 3.8
dist: xenial

services:
  - elasticsearch
  - mysql
  - docker
  - postgresql

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - POSTGRES_USER=postgres
    - DATAPROC_TEST_PROJECT_ID=luigi-travistestenvironment
    - GCS_TEST_PROJECT_ID=luigi-travistestenvironment
    - GCS_TEST_BUCKET=luigi-travistestenvironment
    - BQ_TEST_PROJECT_ID=luigi-travistestenvironment
    - BQ_TEST_INPUT_BUCKET=luigi-bigquery-test
    - GOOGLE_APPLICATION_CREDENTIALS=test/gcloud-credentials.json
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=accesskey
    - AWS_SECRET_ACCESS_KEY=secretkey


sudo: false

# Python 3.7 needs to have its dist/sudo flags set in matrix so they don't
# break the other python builds.
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - env: TOXENV=flake8
    - env: TOXENV=docs

    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38-core
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38-dropbox
      if: env(DROPBOX_APP_TOKEN) is present
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38-unixsocket
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38-apache
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38-aws
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38-azureblob
    - python: 3.8
      env: TOXENV=py38-postgres

cache:
  directories:
    - $HOME/.pip-cache

install:
  - pip install requirements/ci.txt

before_install:
  - openssl aes-256-cbc -K $encrypted_e05f6ccc270e_key -iv $encrypted_e05f6ccc270e_iv -in test/gcloud-credentials.json.enc -out test/gcloud-credentials.json -d
    || export DIDNT_CREATE_GCP_CREDS=1

before_script:
  # TODO, only do this step for the postgres environment
  - psql -c 'create database spotify;' -U postgres

  # Create mysql database if possible but fail silently if not available.
  - mysql -e 'create database IF NOT EXISTS luigi_test;' -uroot || true

script:
  - tox --version
  - ./scripts/ci/conditional_tox.sh

branches:
  only:
    - master
